/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gabriel.frame;

import br.com.gabriel.objeto.Aluno;
import br.com.gabriel.objeto.Nota;
import br.com.gabriel.objeto.TipoAvaliacao;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPAluno = new javax.swing.JPanel();
        jBCadastrar = new javax.swing.JButton();
        jLAluno = new javax.swing.JLabel();
        jLMatricula = new javax.swing.JLabel();
        jTMatricula = new javax.swing.JTextField();
        jLNome = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jPNomeDisciplina = new javax.swing.JPanel();
        jLNomeDisciplina = new javax.swing.JLabel();
        jTDisciplina = new javax.swing.JTextField();
        jCombinacao = new javax.swing.JComboBox<>();
        jPNotas = new javax.swing.JPanel();
        jBCalcular = new javax.swing.JButton();
        jLNotas = new javax.swing.JLabel();
        jLN1 = new javax.swing.JLabel();
        jLN2 = new javax.swing.JLabel();
        jLN3 = new javax.swing.JLabel();
        jN4 = new javax.swing.JLabel();
        jTN1 = new javax.swing.JTextField();
        jTN2 = new javax.swing.JTextField();
        jTN3 = new javax.swing.JTextField();
        jTN4 = new javax.swing.JTextField();
        jLCadastroAluno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        jPAluno.setBackground(new java.awt.Color(102, 102, 102));
        jPAluno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPAluno.setForeground(new java.awt.Color(51, 51, 51));

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jLAluno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLAluno.setText("Aluno");

        jLMatricula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLMatricula.setText("Matrícula");

        jLNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNome.setText("Nome");

        javax.swing.GroupLayout jPAlunoLayout = new javax.swing.GroupLayout(jPAluno);
        jPAluno.setLayout(jPAlunoLayout);
        jPAlunoLayout.setHorizontalGroup(
            jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAlunoLayout.createSequentialGroup()
                .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAlunoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLMatricula)
                                .addComponent(jTMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLNome))))
                    .addGroup(jPAlunoLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLAluno))
                    .addGroup(jPAlunoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jBCadastrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPAlunoLayout.setVerticalGroup(
            jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLAluno)
                .addGap(24, 24, 24)
                .addComponent(jLMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCadastrar)
                .addGap(22, 22, 22))
        );

        jPNomeDisciplina.setBackground(new java.awt.Color(102, 102, 102));
        jPNomeDisciplina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLNomeDisciplina.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNomeDisciplina.setText("Nome da Disciplina");

        jCombinacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prova", "Trabalho", "Seminario" }));
        jCombinacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombinacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPNomeDisciplinaLayout = new javax.swing.GroupLayout(jPNomeDisciplina);
        jPNomeDisciplina.setLayout(jPNomeDisciplinaLayout);
        jPNomeDisciplinaLayout.setHorizontalGroup(
            jPNomeDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNomeDisciplinaLayout.createSequentialGroup()
                .addGroup(jPNomeDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNomeDisciplinaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNomeDisciplinaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLNomeDisciplina)))
                .addContainerGap())
            .addGroup(jPNomeDisciplinaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jCombinacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPNomeDisciplinaLayout.setVerticalGroup(
            jPNomeDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNomeDisciplinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLNomeDisciplina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCombinacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPNotas.setBackground(new java.awt.Color(102, 102, 102));
        jPNotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBCalcular.setText("Calcular");
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });

        jLNotas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLNotas.setText("Notas");

        jLN1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLN1.setText("N1");

        jLN2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLN2.setText("N2");

        jLN3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLN3.setText("N3");

        jN4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jN4.setText("N4");

        javax.swing.GroupLayout jPNotasLayout = new javax.swing.GroupLayout(jPNotas);
        jPNotas.setLayout(jPNotasLayout);
        jPNotasLayout.setHorizontalGroup(
            jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNotasLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLNotas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNotasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addComponent(jBCalcular)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPNotasLayout.createSequentialGroup()
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPNotasLayout.createSequentialGroup()
                                .addComponent(jLN1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTN1))
                            .addGroup(jPNotasLayout.createSequentialGroup()
                                .addComponent(jLN2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTN2))
                            .addGroup(jPNotasLayout.createSequentialGroup()
                                .addComponent(jLN3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTN3))
                            .addGroup(jPNotasLayout.createSequentialGroup()
                                .addComponent(jN4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTN4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPNotasLayout.setVerticalGroup(
            jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNotasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLNotas)
                .addGap(23, 23, 23)
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLN1)
                    .addComponent(jTN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLN2)
                    .addComponent(jTN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLN3)
                    .addComponent(jTN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jN4)
                    .addComponent(jTN4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jBCalcular)
                .addContainerGap())
        );

        jLCadastroAluno.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLCadastroAluno.setText("Cadastro Aluno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPNomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLCadastroAluno)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCadastroAluno)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPNomeDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCombinacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombinacaoActionPerformed
        
    }//GEN-LAST:event_jCombinacaoActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        String nome = jTNome.getText();
        int matricula = 0;
        try {
            matricula = Integer.parseInt(jTMatricula.getText());
        } catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Você digitou um caracter inválido \n"+ nfe);
            throw new RuntimeException();
        }
        Aluno a = new Aluno(nome, matricula);
        JOptionPane.showMessageDialog(this, a.toString());
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
        Aluno a = new Aluno(jTNome.getText(), Integer.parseInt(jTMatricula.getText()));
        TipoAvaliacao tipo = null;
        switch(jCombinacao.getSelectedIndex()){
            case 0:
            {
             tipo = TipoAvaliacao.PROVA;
             break;
            }
            case 1:
            {
             tipo = TipoAvaliacao.SEMINARIO;  
             break;
            }
            case 2:
            {
             tipo = TipoAvaliacao.TRABALHO;
             break;
            }    
        }
        try {
        a.getNotas().add(new Nota(jTDisciplina.getText(), tipo, Float.parseFloat((jTN1.getText()))));
        } catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Você digitou um caracter inválido \n"+ nfe);
            throw new RuntimeException();
        }
        try {
        a.getNotas().add(new Nota(jTDisciplina.getText(), tipo, Float.parseFloat((jTN2.getText()))));
        } catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Você digitou um caracter inválido \n"+ nfe);
            throw new RuntimeException();
        }
        try {
        a.getNotas().add(new Nota(jTDisciplina.getText(), tipo, Float.parseFloat((jTN3.getText()))));
        } catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Você digitou um caracter inválido \n"+ nfe);
            throw new RuntimeException();
        }
        try {
        a.getNotas().add(new Nota(jTDisciplina.getText(), tipo, Float.parseFloat((jTN4.getText()))));
        } catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Você digitou um caracter inválido \n"+ nfe);
            throw new RuntimeException();
        }
        JOptionPane.showMessageDialog(null, a.toString()
                + "\n" + "Média: " + a.calcularMedia());
    }//GEN-LAST:event_jBCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBCalcular;
    private javax.swing.JComboBox<String> jCombinacao;
    private javax.swing.JLabel jLAluno;
    private javax.swing.JLabel jLCadastroAluno;
    private javax.swing.JLabel jLMatricula;
    private javax.swing.JLabel jLN1;
    private javax.swing.JLabel jLN2;
    private javax.swing.JLabel jLN3;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLNomeDisciplina;
    private javax.swing.JLabel jLNotas;
    private javax.swing.JLabel jN4;
    private javax.swing.JPanel jPAluno;
    private javax.swing.JPanel jPNomeDisciplina;
    private javax.swing.JPanel jPNotas;
    private javax.swing.JTextField jTDisciplina;
    private javax.swing.JTextField jTMatricula;
    private javax.swing.JTextField jTN1;
    private javax.swing.JTextField jTN2;
    private javax.swing.JTextField jTN3;
    private javax.swing.JTextField jTN4;
    private javax.swing.JTextField jTNome;
    // End of variables declaration//GEN-END:variables

 
        }